version: "3.0"

services:
  django:
    build: 
      context: .
      dockerfile: django.Dockerfile
    ports:
      - 8000:8000
  react:
    build: 
      context: .
      dockerfile: react.Dockerfile
    ports:
      - 3000:3000